### ISSUE TITLE
Multi element support

### ISSUE THREAD

**Issue by Link2Twenty** [prateekjadhwani/podcast-player#16]
When I try to run the new demo with multiple uses of the element this happens.

![issue](https://cloud.githubusercontent.com/assets/3534427/8670115/eae22770-2a11-11e5-813f-1613564e5950.gif)

**Comment by prateekjadhwani** [comment]
I am not able to replicate the issue. Do you see any console logs/errors?

**Comment by Link2Twenty** [comment]
![issue](https://cloud.githubusercontent.com/assets/3534427/8670932/dfa3bcf0-2a18-11e5-8df8-f5091b397f64.png)
Might be caused by pressing pause before the wave loads in?

**Comment by prateekjadhwani** [comment]
Nope, still cant replicate.

**Comment by Link2Twenty** [comment]
It appears to be an issue with the devices storage (ram) getting too full,
possible solution, 
clear storage when opening new podcast-player
clear storage when ever paused (but store new start place)
buffering is another option, but the wave won't won't load in if that's the case https://github.com/katspaugh/wavesurfer.js/issues/369
maybe have a fancy mode, that uses the wave and normal mode that uses paper-pregress?

**Comment by prateekjadhwani** [comment]
I agree wit you. I need to look into multiple modes for better memory management.

**Comment by prateekjadhwani** [comment]
Fixed in https://github.com/prateekjadhwani/podcast-player/commit/60bb5ab8aa20d1c1a82f36b94b96cec441ff93b9
