### ISSUE TITLE
Wave Parsing

### ISSUE THREAD

**Issue by Link2Twenty** [prateekjadhwani/podcast-player#18]
Looking into how to make the wave in other methods.
Some light reading:
- https://github.com/afreiday/php-waveform-svg
- https://github.com/bbcrd/peaks.js
- http://www.bbc.co.uk/rd/blog/2013/10/audio-waveforms
- https://github.com/haochuan/Waveform-Display
- https://authenticstyle.co.uk/html5-audio-player-8/
- http://webdesign.tutsplus.com/tutorials/create-a-customized-html5-audio-player--webdesign-7081

**Comment by prateekjadhwani** [comment]
Completed in https://github.com/prateekjadhwani/podcast-player/commit/3861fea030ca915cae0359183f2b25ebc7f0be07
