### ISSUE TITLE
Inspiration for UI

### ISSUE THREAD

**Issue by Link2Twenty** [prateekjadhwani/podcast-player#4]
http://www.materialup.com/posts/material-design-the-morphing-fab

Using neon-animated-pages

**Comment by prateekjadhwani** [comment]
:+1: 

Totally need to apply this!!

**Comment by prateekjadhwani** [comment]
Fixed in https://github.com/prateekjadhwani/podcast-player/commit/10413fc7656601ac12e95836eed43a489e18594d
