### ISSUE TITLE
Implement Finish event

### ISSUE THREAD

**Issue by prateekjadhwani** [prateekjadhwani/podcast-player#5]
Right now the pause button doesnt turn back to the play button when the music completes playing. Implementation of the finish event for `wavesurfer` should take care of that.

**Comment by Link2Twenty** [comment]
This at the edit of initWaveSurfer should solve the issue (where code is changing the icon)

this.wavesurfer.on('finish', function () {
    // code
});

**Comment by prateekjadhwani** [comment]
Fixed in https://github.com/prateekjadhwani/podcast-player/commit/10413fc7656601ac12e95836eed43a489e18594d
